on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]


name: Test

jobs:
  build:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        features: [""]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install
        run: python3 setup.py install --user

      - name: Test
        run: test/test_networks.sh
